# Generated by Django 6.0.5 on 2026-06-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_rename_price_total_order_total_price_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="Product",
            new_name="product",
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
